### ISSUE TITLE
Should be able to remove files in the placeholder

### ISSUE THREAD

**Issue by boutzamat** [QuickenLoans/jquery-imageuploader-js#3]
Awesome plugin!
It lacks the possibility to remove a file that has been added to the upload queue..

**Comment by RCopeland** [comment]
Thanks!
It does add the little X's when you select a file to be uploaded. If you click them they should get removed. 
Is that what you mean?

**Comment by boutzamat** [comment]
Oh, i didnt notice, but yeah that is exactly what i mean :) 
I'll check again :) 

Closing this issue.

**Comment by novazz** [comment]
where is that little X? i don't see it
