### ISSUE TITLE
How can I delete wrong selected files?

### ISSUE THREAD

**Issue by novazz** [QuickenLoans/jquery-imageuploader-js#8]
Is there a little X to be clicked? where is it

**Comment by RCopeland** [comment]
Its a font-awesome icon, the class that adds it is here: https://github.com/QuickenLoans/jquery-imageuploader-js/blob/master/dist/jquery.imageuploader.js#L118
Do you have font-awesome installed?

**Comment by novazz** [comment]
> Its a font-awesome icon, the class that adds it is here: https://github.com/QuickenLoans/jquery-imageuploader-js/blob/master/dist/jquery.imageuploader.js#L118
> Do you have font-awesome installed?

thanks
